get http://localhost:3000/patient/
Content-Type:  application/json

{
    "last_name": "Mark ",
    "first_name": "ZAKZAK",
    "initials": "MZ",
    "age": 155,
    "gender": "Male",
    "race": "Silver",
}